name: Auto-Update Datasets

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update all datasets'
        required: false
        default: 'false'
        type: boolean

jobs:
  auto-update-datasets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Auto-detect new datasets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FORCE_UPDATE: ${{ github.event.inputs.force_update }}
      run: |
        python auto_detect_datasets.py

    - name: Generate dataset markdown files
      run: |
        python generate_dataset_files.py

    - name: Validate datasets
      run: |
        python validate_datasets.py

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "🤖 Auto-update datasets: $(date '+%Y-%m-%d %H:%M:%S')"
        git push

    - name: Create summary
      if: steps.changes.outputs.changes == 'true'
      run: |
        echo "## 🔄 Dataset Auto-Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Changes detected**: Yes" >> $GITHUB_STEP_SUMMARY
        echo "- **Files updated**:" >> $GITHUB_STEP_SUMMARY
        git diff --name-only HEAD~1 HEAD | sed 's/^/  - /' >> $GITHUB_STEP_SUMMARY

    - name: No changes summary
      if: steps.changes.outputs.changes == 'false'
      run: |
        echo "## ✅ Dataset Auto-Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Changes detected**: No new datasets found" >> $GITHUB_STEP_SUMMARY
