name: Keep Hugging Face Spaces Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq ripgrep

      - name: Collect Space URLs
        id: collect
        run: |
          set -e
          # From playground data
          jq -r '..|strings|select(test("^https://huggingface.co/spaces/"))' _data/smolhub_playground.json || true > /tmp/urls1.txt

          # Also scan project markdown and includes for any HF Spaces links
          rg -No --glob '!node_modules' 'https://huggingface\.co/spaces/\S+' || true > /tmp/urls2.txt

          # Merge, dedupe, and basic sanitize (strip trailing punctuation)
          cat /tmp/urls1.txt /tmp/urls2.txt | sed 's/[),.\"]$//' | sort -u > /tmp/urls.txt

          echo "Found URLs:" && cat /tmp/urls.txt || true

          count=$(wc -l < /tmp/urls.txt | tr -d ' ')
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Ping Spaces (root and queue)
        if: steps.collect.outputs.count != '0'
        run: |
          set -e
          while IFS= read -r url; do
            echo "Pinging $url"
            # Try HEAD first, then GET fallback
            (curl -sS -I "$url" || curl -sS "$url" >/dev/null) || true
            # Ping with a cache-busting param
            (curl -sS -I "$url?noCache=$(date +%s)" || true)
            # If it's a Gradio space, also hit the queue endpoint to warm it
            proto_host=$(echo "$url" | awk -F/ '{print $1"//"$3}')
            (curl -sS -I "$proto_host/queue/join" || true)
          done < /tmp/urls.txt

      - name: Summary
        run: |
          echo "Pinged $(wc -l < /tmp/urls.txt | tr -d ' ') Hugging Face Spaces URLs."


