name: Update Datasets Data

# Permissions needed for the workflow
permissions:
  contents: write
  pull-requests: write

on:
  # Run weekly on Saturdays at 6 AM UTC (one day before models)
  schedule:
    - cron: '0 6 * * 6'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run when datasets.json or scripts are updated
  push:
    paths:
      - '_data/datasets.json'
      - 'fetch_github_dates.py'
      - '_datasets/*.md'

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Update datasets with GitHub creation dates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "📅 Fetching GitHub creation dates for datasets..."
        python fetch_github_dates.py
        echo "✅ Datasets updated with real GitHub commit dates"
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Pull latest changes first to avoid conflicts
        git pull origin master --rebase || {
          echo "⚠️ Rebase conflicts detected, trying merge strategy"
          git rebase --abort 2>/dev/null || true
          git pull origin master --no-rebase
        }
        
        git add .
        git commit -m "📅 Auto-update datasets with GitHub creation dates" || {
          echo "⚠️ Nothing to commit or commit failed"
          exit 0
        }
        
        # Try to push, with retry logic
        for i in {1..3}; do
          if git push; then
            echo "✅ Push successful on attempt $i"
            break
          else
            echo "⚠️ Push failed on attempt $i, pulling latest changes..."
            git pull origin master --rebase
            if [ $i -eq 3 ]; then
              echo "❌ Failed to push after 3 attempts"
              exit 1
            fi
          fi
        done 
